### ISSUE TITLE
Project-specific GOPATH

### ISSUE THREAD

**Issue by aemreunal** [sirreal/SublimeLinter-contrib-golint#5]
Hello,
I'm trying to set up project-specific GOPATH for the linter but I can't seem to do it. This is the `.sublime-project` file I have right now:
```json
{
    "SublimeLinter": {
        "linters": {
            "golint": {
                "GOPATH": "..."
            }
        }
    },
    "folders": [ ... ],
    "settings": {
        "GoSublime": {
            "env": {
                "GOPATH": "..."
            }
        }
    }
}
```
It seems like this linter is not picking up on the GOPATH I specified for it. Is my syntax wrong?
Thank you.

**Comment by sirreal** [comment]
Sorry to let this sit for so long. I really don't use this project and can't handle maintenance.
